#!/bin/bash
#  install the ufw firewall and setup a few rules on web-01
sudo apt update
sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disabl
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp 
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp 

sudo ufw status
