#!/bin/bash
# Configures a ufw firewall to block all incoming traffic
sudo sysctl -w net.ipv4.ip_forward=1
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
sudo ufw route allow proto tcp from any to any port 8080
sudo ufw reload
